### ISSUE TITLE
New DragBackdrop frame fix not working as intended

### ISSUE THREAD

**Issue by tflo** [Imaginary-Narwhal/ToyJunkie#4]
In https://github.com/Imaginary-Narwhal/ToyJunkie/commit/51b9d63747f3bcd7cb9b9a00c8af8dfb81aedf8d, you merged my PR https://github.com/Imaginary-Narwhal/ToyJunkie/pull/2, in order to prevent the DragBackdrop frame from being there when it shouldn't (blocking mouse interaction).

In https://github.com/Imaginary-Narwhal/ToyJunkie/commit/44b97870f4a6e1a6c84cfff3010a83f25628a35b, you reverted the change from the PR and applied a [more comprehensive fix in DragFrame.lua](https://github.com/Imaginary-Narwhal/ToyJunkie/commit/44b97870f4a6e1a6c84cfff3010a83f25628a35b#diff-0725513363ae0b7ab81223d52569ec9ecea44057686a7509254dbf301d648f45).

But with that, the faulty behavior is back (at least for me). The reason seems to be again an `IsShown` (instead of `IsVisible`), this time for the ToyBox frame. This fixes it for me:

```diff
--- /Users/tom/.tmpfs_devices/F26E5D/Tmp-4G/DragFrame.lua	2024-09-13 14:02:44.000000000 
+++ /Users/tom/.tmpfs_devices/F26E5D/Tmp-4G/DragFrame-fix.lua	2024-09-13 13:32:26.000000000 
@@ -9,13 +9,13 @@
 L.ToyJunkie.DragBackdrop = CreateFrame("Button", "ToyJunkie_DragBackdrop", UIParent)
 L.ToyJunkie.DragBackdrop:SetFrameStrata("LOW")
 L.ToyJunkie.DragBackdrop:SetFrameLevel(0)
 L.ToyJunkie.DragBackdrop:SetAllPoints()
 L.ToyJunkie.DragBackdrop:Hide()
 L.ToyJunkie.DragBackdrop:SetScript("OnShow", function(self)
-    if(ToyBox:IsShown()) then
+    if(ToyBox:IsVisible()) then
         L.AttachedFrame.ScrollFrame.listView:RegisterEvent("GLOBAL_MOUSE_UP")
     else
         L.ToyJunkie.DragBackdrop:Hide()
     end
 end)
 L.ToyJunkie.DragBackdrop:SetScript("OnHide", function(self)
```

When testing, remember that the issue is only exposed if the ToyBox has been opened once since login.

---

PS:

You can easily verify the visibility state of the ToyBox frame in-game:

1. Open ToyBox, close it again.
2. Run this in the chat console: `/run print(ToyBox:IsShown())` --> returns true
3. Run this in the chat console: `/run print(ToyBox:IsVisible())` --> returns false

For the difference IsShown/IsVisible, see [here](https://warcraft.wiki.gg/wiki/API_ScriptRegion_IsShown).

**Comment by Imaginary-Narwhal** [comment]
Thank you for the info. Pushed an update (and had issues over at curseforge with the upload). Should be fixed now, and added another level of hiding the frame. If you still have issues after the update, please make a new issue.
