### ISSUE TITLE
`ToyboxWindow.lua:418: attempt to index field '?' (a nil value)`

### ISSUE THREAD

**Issue by tflo** [Imaginary-Narwhal/ToyJunkie#5]
For a while now I’m getting this error when I open a certain ToyJunkie toy box (click triangle to open):

<details>
<summary><code>ToyboxWindow.lua:418: attempt to index field '?' (a nil value)</code></summary>

```denizenscript
1x ToyJunkie/Windows/ToyboxWindow.lua:418: attempt to index field '?' (a nil value)
[string "@ToyJunkie/Windows/ToyboxWindow.lua"]:418: in function `UpdateToyButtons'
[string "@ToyJunkie/ScrollTemplate/ToyboxScrollFrame.lua"]:107: in function <...ddOns/ToyJunkie/ScrollTemplate/ToyboxScrollFrame.lua:102>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@ToyJunkie/ScrollTemplate/ToyboxScrollFrame.lua"]:20: in function <...ddOns/ToyJunkie/ScrollTemplate/ToyboxScrollFrame.lua:19>

Locals:
self = ToyJunkie_ToyboxFrame {
 BottomLeftCorner = Texture {
 }
 RandomHearthstoneButton = ToyJunkie_ToyboxFrame_RandomHearthstoneButton {
 }
 TopLeftCorner = Texture {
 }
 RightEdge = Texture {
 }
 RandomToyButton = ToyJunkie_ToyboxFrame_RandomToyButton {
 }
 LockButton = ToyJunkie_ToyboxFrame_LockButton {
 }
 SideMenuButton = ToyJunkie_ToyboxFrame_SideMenuButton {
 }
 backdropInfo = <table> {
 }
 TopRightCorner = Texture {
 }
 ResizeButton = ToyJunkie_ToyboxFrame_ResizeButton {
 }
 ToyButtons = <table> {
 }
 ToyButtonHolderFrame = ToyJunkie_ToyboxFrame_ToyButtonHolderFrame {
 }
 SideMenuBar = ToyJunkie_ToyboxFrame_SideMenuBar {
 }
 TopEdge = Texture {
 }
 SettingsButton = ToyJunkie_ToyboxFrame_SettingsButton {
 }
 Center = Texture {
 }
 CloseButton = ToyJunkie_ToyboxFrame_CloseButton {
 }
 BottomEdge = Texture {
 }
 LeftEdge = Texture {
 }
 BottomRightCorner = Texture {
 }
}
numToyboxToys = 18
numStoredToys = 19
b = 20
(for state) = <table> {
 1 = 166247
 2 = 166808
 3 = 119001
 4 = 88579
 5 = 33927
 6 = 33219
 7 = 169865
 8 = 207092
 9 = 206565
 10 = 200707
 11 = 224783
 12 = 139337
 13 = 71137
 14 = 186974
 15 = 200628
 16 = 38301
 17 = 208883
 18 = 88387
 20 = 151877
 21 = 120857
}
(for control) = 21
k = 21
toyId = 120857
(*temporary) = nil
(*temporary) = 120857
(*temporary) = 12
(*temporary) = 12
(*temporary) = <table> {
 toys = <table> {
 }
 name = "Interact: Buffet"
 isCollapsed = false
 icon = 3671903
 toyColor = <table> {
 }
}
(*temporary) = "interact: buffet"
(*temporary) = "interact: buffet"
(*temporary) = "Interact: Buffet"
(*temporary) = "interact: buffet"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
L = <table> {
 defaults = <table> {
 }
 HearthstoneIds = <table> {
 }
 catID = "ToyJunkie"
 AttachedScrollTemplateMixin = <table> {
 }
 ToyboxFrame = ToyJunkie_ToyboxFrame {
 }
 AttachedFrame = ToyJunkie_CollectionAttachedFrame {
 }
 ToyboxSelectionTemplateMixin = <table> {
 }
 isInCombat = false
 Icons = <table> {
 }
 ToyJunkie = <table> {
 }
}

```
</details>

This happens often, but (I think?) not in each and every session. 

When it happens, it blocks any further opening of ToyJunkie boxes.

Obviously I can prevent the error by adding a nil check…

```diff
diff --git a/ToyJunkie/Windows/ToyboxWindow.lua b/ToyJunkie/Windows/ToyboxWindow.lua
--- a/ToyJunkie/Windows/ToyboxWindow.lua
+++ b/ToyJunkie/Windows/ToyboxWindow.lua
@@ -417,4 +417,4 @@
         for k, toyId in pairs(L.ToyJunkie.db.profile.boxes[L:GetToyBoxIdByName(L.ToyJunkie.db.profile.selectedToybox)].toys) do
-            L.ToyboxFrame.ToyButtons[b].id = toyId
+            if L.ToyboxFrame.ToyButtons[b] then L.ToyboxFrame.ToyButtons[b].id = toyId end
             b = b + 1
         end
```

…but this doesn’t explain why the error occurs. It seems your `b` counter gets out of range of the existing table indexes, but I have no clue why this happens and why only with one specific toy box and why it does not happen every time.

I guess something is bogus with that specific toy box table. Hence here a copy of my SavedVariables file from after a session where I got the error:

[ToyJunkie.lua.zip](https://github.com/user-attachments/files/17691004/ToyJunkie.lua.zip)

The problematic box is always "Interact: Buffet". Maybe you can figure out what is going wrong.

**Comment by Imaginary-Narwhal** [comment]
So the errors you are getting is from before version 1.1 where I had a bug that could add a nil space between two toys in the table. I fixed the ability for the code to create the nil space, but any that was already messed up carried over. To fix it, what I can do is create a slash command in the main program to go through and clean up your tables to make sure everything is correct. It will take me a little time to do this, but keep an eye out for an update.

**Comment by tflo** [comment]
> bug that could add a nil space

You mean line 537? (in the uploaded file)

While skimming through the file, why do some tables have a few explicit and non-consecutive integer keys, with the rest of the table being like an array? (e.g. lines 465/466)

**Comment by Imaginary-Narwhal** [comment]
> > bug that could add a nil space
> 
> You mean line 537? (in the uploaded file)
> 
> While skimming through the file, why do some tables have a few explicit and non-consecutive integer keys, with the rest of the table being like an array? (e.g. lines 465/466)

Yes. That was an issue with moving toys around in the edit window. It would move a toy to the next number then add one to the index (ie. toy was at index 11, move it and now it's at 13 leaving 12 empty.) The new command that I created should fix that for all tables that are messed up. The adding a number to the index was also fixed but didn't retroactively fix the tables. 

Once the new update is available (should be a few minutes) you can run the game, type **/tj clean** and then **/reload** and it should solve the problem. If not, please let me know. Will leave this issue open for a day or two.

**Comment by tflo** [comment]
OK, I updated, tested if it bugged out again (and it did), ran the `/tj clean`, reloaded and no error anymore (without the nil check) ☺️ The saved tables look clean now.

Great (and fast) job! Thank you!

**Comment by Imaginary-Narwhal** [comment]
You are welcome, thank you for bringing to my attention.
